import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:net';
import { setTimeout as delay } from 'node:timers/promises';
import { MongoOAuthStore } from '../src/auth/store.js';

const available = spawnSync('mongod', ['--version'], { stdio: 'ignore' }).status === 0;
test('real MongoDB persists encrypted grants across clients and redeems atomically', { skip: !available, timeout: 20000 }, async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'postmcp-oauth-test-'));
  const socket = createServer();
  await new Promise((resolve) => socket.listen(0, '127.0.0.1', resolve));
  const port = socket.address().port;
  await new Promise((resolve) => socket.close(resolve));
  const mongo = spawn('mongod', ['--dbpath', dir, '--bind_ip', '127.0.0.1', '--port', String(port), '--quiet'], { stdio: 'ignore' });
  const exited = new Promise((resolve) => mongo.once('exit', resolve));
  const uri = `mongodb://127.0.0.1:${port}/postmcp_oauth_test`;
  const a = new MongoOAuthStore(uri, 'a'.repeat(64));
  const b = new MongoOAuthStore(uri, 'a'.repeat(64));
  t.after(async () => { await a.close(); await b.close(); mongo.kill('SIGTERM'); await exited; await rm(dir, { recursive: true, force: true }); });
  await delay(500);
  const collection = await a.collection();
  const value = { apiKey: 'test-secret-credential', scopes: ['mcp'] };
  await a.put('grant', 'grant-id', value, Date.now() + 60000);
  assert.equal((await b.get('grant', 'grant-id')).apiKey, value.apiKey);
  const stored = await collection.findOne({});
  assert.ok(!JSON.stringify(stored).includes(value.apiKey));
  assert.ok(!stored._id.includes('grant-id'));
  const indexes = await collection.indexes();
  assert.ok(indexes.some((index) => index.expireAfterSeconds === 0));
  const results = await Promise.all([a.consume('grant', 'grant-id'), b.consume('grant', 'grant-id')]);
  assert.equal(results.filter(Boolean).length, 1);
  assert.equal((await b.get('grant', 'grant-id')).used, true);
  await a.put('access', 'expired', value, Date.now() - 1);
  assert.equal(await b.get('access', 'expired'), null);
  await b.delete('grant', 'grant-id');
  assert.equal(await a.get('grant', 'grant-id'), null);
});
